# Generated by Django 2.1 on 2018-08-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('replies', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
