# Generated by Django 2.1.2 on 2018-11-04 02:52

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, choices=[('Canada', 'Canada'), ('AB', 'AB'), ('BC', 'BC'), ('MB', 'MB'), ('NB', 'NB'), ('NS', 'NS'), ('ON', 'ON'), ('PEI', 'PEI'), ('QB', 'QB'), ('SK', 'SK'), ('Territories', 'Territories')], default='Canada', help_text='Location', max_length=50)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('replies', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(blank=True, max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MPTTComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=12)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentss', to='portfolio.Board')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='portfolio.MPTTComment')),
            ],
            options={
                'ordering': ['author'],
            },
        ),
    ]
