# Generated by Django 2.1 on 2018-08-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
