# Generated by Django 2.1 on 2018-08-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_board_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='location',
            field=models.CharField(blank=True, choices=[('Canada', 'Canada'), ('Manitoba', 'Manitoba'), ('British Columbia', 'British Columbia'), ('Alberta', 'Alberta')], default='Canada', help_text='Location', max_length=50),
        ),
    ]
