# Generated by Django 2.1 on 2018-09-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20180828_0151'),
    ]

    operations = [
    ]
