# Generated by Django 2.1 on 2018-09-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20180901_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='location',
        ),
    ]
