# Generated by Django 2.1 on 2018-09-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_board_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='location',
            field=models.CharField(blank=True, choices=[('Canada', 'Canada'), ('AB', 'AB'), ('BC', 'BC'), ('MB', 'MB'), ('NB', 'NB'), ('NS', 'NS'), ('ON', 'ON'), ('PEI', 'PEI'), ('QB', 'QB'), ('SK', 'SK'), ('Territories', 'Territories')], default='Canada', help_text='Location', max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
